"""update

Revision ID: 8d26cf0f6a05
Revises: 64fb17f9de34
Create Date: 2025-11-26 17:41:11.042603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d26cf0f6a05'
down_revision: Union[str, Sequence[str], None] = '64fb17f9de34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'intensity')
    op.drop_column('images', 'is_fill')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_fill', sa.BOOLEAN(), nullable=True))
    op.add_column('images', sa.Column('intensity', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
